# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analizador-form-1-0.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1254, 654)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblimg1 = ScaledLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblimg1.sizePolicy().hasHeightForWidth())
        self.lblimg1.setSizePolicy(sizePolicy)
        self.lblimg1.setMaximumSize(QtCore.QSize(960, 540))
        self.lblimg1.setFrameShape(QtWidgets.QFrame.Box)
        self.lblimg1.setObjectName("lblimg1")
        self.verticalLayout.addWidget(self.lblimg1)
        self.lblimg2 = ScaledLabel(self.centralwidget)
        self.lblimg2.setFrameShape(QtWidgets.QFrame.Box)
        self.lblimg2.setObjectName("lblimg2")
        self.verticalLayout.addWidget(self.lblimg2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.lblimg3 = ScaledLabel(self.centralwidget)
        self.lblimg3.setMaximumSize(QtCore.QSize(1920, 1080))
        self.lblimg3.setFrameShape(QtWidgets.QFrame.Box)
        self.lblimg3.setObjectName("lblimg3")
        self.horizontalLayout.addWidget(self.lblimg3)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnAnterior = QtWidgets.QPushButton(self.centralwidget)
        self.btnAnterior.setMinimumSize(QtCore.QSize(0, 25))
        self.btnAnterior.setObjectName("btnAnterior")
        self.horizontalLayout_2.addWidget(self.btnAnterior)
        self.btnEventAnt = QtWidgets.QToolButton(self.centralwidget)
        self.btnEventAnt.setMinimumSize(QtCore.QSize(0, 25))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Documentos/ingenia/revwin-1-0/analizador/img_default/1leftarrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEventAnt.setIcon(icon)
        self.btnEventAnt.setObjectName("btnEventAnt")
        self.horizontalLayout_2.addWidget(self.btnEventAnt)
        self.tbtnPlay = QtWidgets.QToolButton(self.centralwidget)
        self.tbtnPlay.setMinimumSize(QtCore.QSize(0, 25))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Documentos/ingenia/revwin-1-0/analizador/img_default/player_play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbtnPlay.setIcon(icon1)
        self.tbtnPlay.setObjectName("tbtnPlay")
        self.horizontalLayout_2.addWidget(self.tbtnPlay)
        self.lblvelocidad = QtWidgets.QLabel(self.centralwidget)
        self.lblvelocidad.setMinimumSize(QtCore.QSize(0, 25))
        self.lblvelocidad.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lblvelocidad.setObjectName("lblvelocidad")
        self.horizontalLayout_2.addWidget(self.lblvelocidad)
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setMinimumSize(QtCore.QSize(0, 25))
        self.spinBox.setMaximumSize(QtCore.QSize(60, 16777215))
        self.spinBox.setMinimum(100)
        self.spinBox.setMaximum(2000)
        self.spinBox.setSingleStep(100)
        self.spinBox.setProperty("value", 500)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_2.addWidget(self.spinBox)
        self.btnEventSig = QtWidgets.QToolButton(self.centralwidget)
        self.btnEventSig.setMinimumSize(QtCore.QSize(0, 25))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Documentos/ingenia/revwin-1-0/analizador/img_default/1rightarrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEventSig.setIcon(icon2)
        self.btnEventSig.setObjectName("btnEventSig")
        self.horizontalLayout_2.addWidget(self.btnEventSig)
        self.btnSiguiente = QtWidgets.QPushButton(self.centralwidget)
        self.btnSiguiente.setMinimumSize(QtCore.QSize(0, 25))
        self.btnSiguiente.setFlat(False)
        self.btnSiguiente.setObjectName("btnSiguiente")
        self.horizontalLayout_2.addWidget(self.btnSiguiente)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.lstParametros = QtWidgets.QListWidget(self.centralwidget)
        self.lstParametros.setObjectName("lstParametros")
        item = QtWidgets.QListWidgetItem()
        self.lstParametros.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstParametros.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstParametros.addItem(item)
        self.gridLayout.addWidget(self.lstParametros, 1, 1, 2, 1)
        self.combCategoria = QtWidgets.QComboBox(self.centralwidget)
        self.combCategoria.setObjectName("combCategoria")
        self.gridLayout.addWidget(self.combCategoria, 1, 2, 1, 1)
        self.lstEventos = QtWidgets.QListWidget(self.centralwidget)
        self.lstEventos.setObjectName("lstEventos")
        self.gridLayout.addWidget(self.lstEventos, 1, 4, 2, 1)
        self.btnElimEvento = QtWidgets.QPushButton(self.centralwidget)
        self.btnElimEvento.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Documentos/ingenia/revwin-1-0/analizador/img_default/edit_remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnElimEvento.setIcon(icon3)
        self.btnElimEvento.setObjectName("btnElimEvento")
        self.gridLayout.addWidget(self.btnElimEvento, 1, 5, 2, 1)
        self.sldrPosicion = QtWidgets.QSlider(self.centralwidget)
        self.sldrPosicion.setOrientation(QtCore.Qt.Horizontal)
        self.sldrPosicion.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.sldrPosicion.setTickInterval(10)
        self.sldrPosicion.setObjectName("sldrPosicion")
        self.gridLayout.addWidget(self.sldrPosicion, 2, 0, 1, 1)
        self.lnValor = QtWidgets.QLineEdit(self.centralwidget)
        self.lnValor.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnValor.sizePolicy().hasHeightForWidth())
        self.lnValor.setSizePolicy(sizePolicy)
        self.lnValor.setMinimumSize(QtCore.QSize(60, 25))
        self.lnValor.setMaximumSize(QtCore.QSize(60, 25))
        self.lnValor.setObjectName("lnValor")
        self.gridLayout.addWidget(self.lnValor, 2, 2, 1, 1)
        self.btnAgregarEvento = QtWidgets.QPushButton(self.centralwidget)
        self.btnAgregarEvento.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../Documentos/ingenia/revwin-1-0/analizador/img_default/edit_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAgregarEvento.setIcon(icon4)
        self.btnAgregarEvento.setObjectName("btnAgregarEvento")
        self.gridLayout.addWidget(self.btnAgregarEvento, 1, 3, 1, 1)
        self.lstEventos.raise_()
        self.btnElimEvento.raise_()
        self.lstParametros.raise_()
        self.lnValor.raise_()
        self.sldrPosicion.raise_()
        self.lblvelocidad.raise_()
        self.lblvelocidad.raise_()
        self.combCategoria.raise_()
        self.btnAgregarEvento.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1254, 27))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuVer = QtWidgets.QMenu(self.menubar)
        self.menuVer.setObjectName("menuVer")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbrir = QtWidgets.QAction(MainWindow)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionDefault = QtWidgets.QAction(MainWindow)
        self.actionDefault.setObjectName("actionDefault")
        self.actionInfo = QtWidgets.QAction(MainWindow)
        self.actionInfo.setObjectName("actionInfo")
        self.actionEstad_sticas = QtWidgets.QAction(MainWindow)
        self.actionEstad_sticas.setObjectName("actionEstad_sticas")
        self.actionGuardar = QtWidgets.QAction(MainWindow)
        self.actionGuardar.setObjectName("actionGuardar")
        self.actionExportar_ANAX = QtWidgets.QAction(MainWindow)
        self.actionExportar_ANAX.setObjectName("actionExportar_ANAX")
        self.actionExportar_CSV = QtWidgets.QAction(MainWindow)
        self.actionExportar_CSV.setObjectName("actionExportar_CSV")
        self.actionCambiar_Editar_Perfil = QtWidgets.QAction(MainWindow)
        self.actionCambiar_Editar_Perfil.setObjectName("actionCambiar_Editar_Perfil")
        self.menuArchivo.addAction(self.actionAbrir)
        self.menuArchivo.addAction(self.actionGuardar)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionExportar_ANAX)
        self.menuArchivo.addAction(self.actionExportar_CSV)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionSalir)
        self.menuVer.addAction(self.actionCambiar_Editar_Perfil)
        self.menuVer.addAction(self.actionInfo)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuVer.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblimg1.setText(_translate("MainWindow", "TextLabel"))
        self.lblimg2.setText(_translate("MainWindow", "TextLabel"))
        self.lblimg3.setText(_translate("MainWindow", "TextLabel"))
        self.btnAnterior.setText(_translate("MainWindow", "Anterior"))
        self.btnEventAnt.setText(_translate("MainWindow", "..."))
        self.tbtnPlay.setText(_translate("MainWindow", "..."))
        self.lblvelocidad.setText(_translate("MainWindow", "Vel [ms]"))
        self.btnEventSig.setText(_translate("MainWindow", "..."))
        self.btnSiguiente.setText(_translate("MainWindow", "Siguiente"))
        __sortingEnabled = self.lstParametros.isSortingEnabled()
        self.lstParametros.setSortingEnabled(False)
        item = self.lstParametros.item(0)
        item.setText(_translate("MainWindow", "Exudacion"))
        item = self.lstParametros.item(1)
        item.setText(_translate("MainWindow", "Bacheo"))
        item = self.lstParametros.item(2)
        item.setText(_translate("MainWindow", "Fisuras"))
        self.lstParametros.setSortingEnabled(__sortingEnabled)
        self.lnValor.setPlaceholderText(_translate("MainWindow", "0-999"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.menuVer.setTitle(_translate("MainWindow", "Sesion"))
        self.actionAbrir.setText(_translate("MainWindow", "Abrir"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionDefault.setText(_translate("MainWindow", "Default"))
        self.actionInfo.setText(_translate("MainWindow", "Información de sesion"))
        self.actionEstad_sticas.setText(_translate("MainWindow", "Estadísticas"))
        self.actionGuardar.setText(_translate("MainWindow", "Guardar"))
        self.actionExportar_ANAX.setText(_translate("MainWindow", "Exportar ANAX (Visualizar)"))
        self.actionExportar_CSV.setText(_translate("MainWindow", "Exportar CSV (Excel)"))
        self.actionCambiar_Editar_Perfil.setText(_translate("MainWindow", "Cambiar/Editar Perfil"))

from scaledlabel import ScaledLabel
