# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'perfiles.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(754, 532)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(180, 480, 521, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.combPerfil = QtWidgets.QComboBox(Dialog)
        self.combPerfil.setGeometry(QtCore.QRect(130, 20, 231, 33))
        self.combPerfil.setObjectName("combPerfil")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 30, 56, 17))
        self.label.setObjectName("label")
        self.btnImpPerfil = QtWidgets.QPushButton(Dialog)
        self.btnImpPerfil.setGeometry(QtCore.QRect(500, 50, 131, 27))
        self.btnImpPerfil.setObjectName("btnImpPerfil")
        self.btnExpPerfil = QtWidgets.QPushButton(Dialog)
        self.btnExpPerfil.setGeometry(QtCore.QRect(500, 20, 131, 27))
        self.btnExpPerfil.setObjectName("btnExpPerfil")
        self.lblPerfil = QtWidgets.QLabel(Dialog)
        self.lblPerfil.setGeometry(QtCore.QRect(450, 130, 271, 331))
        self.lblPerfil.setFrameShape(QtWidgets.QFrame.Panel)
        self.lblPerfil.setObjectName("lblPerfil")
        self.btnNuevoPerfil = QtWidgets.QPushButton(Dialog)
        self.btnNuevoPerfil.setGeometry(QtCore.QRect(380, 20, 85, 27))
        self.btnNuevoPerfil.setObjectName("btnNuevoPerfil")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(510, 100, 161, 17))
        self.label_4.setObjectName("label_4")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(30, 70, 311, 241))
        self.groupBox.setObjectName("groupBox")
        self.lnNombreParam = QtWidgets.QLineEdit(self.groupBox)
        self.lnNombreParam.setGeometry(QtCore.QRect(10, 60, 113, 27))
        self.lnNombreParam.setObjectName("lnNombreParam")
        self.lnCodeParam = QtWidgets.QLineEdit(self.groupBox)
        self.lnCodeParam.setGeometry(QtCore.QRect(190, 60, 31, 27))
        self.lnCodeParam.setObjectName("lnCodeParam")
        self.btnAddParam = QtWidgets.QPushButton(self.groupBox)
        self.btnAddParam.setGeometry(QtCore.QRect(240, 60, 41, 27))
        self.btnAddParam.setObjectName("btnAddParam")
        self.btnDelParam = QtWidgets.QPushButton(self.groupBox)
        self.btnDelParam.setGeometry(QtCore.QRect(230, 150, 31, 27))
        self.btnDelParam.setObjectName("btnDelParam")
        self.lstCategorias = QtWidgets.QListWidget(self.groupBox)
        self.lstCategorias.setGeometry(QtCore.QRect(10, 100, 191, 121))
        self.lstCategorias.setObjectName("lstCategorias")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 320, 341, 191))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lnCategorias = QtWidgets.QLineEdit(self.groupBox_2)
        self.lnCategorias.setGeometry(QtCore.QRect(10, 30, 113, 27))
        self.lnCategorias.setObjectName("lnCategorias")
        self.btnAddCat = QtWidgets.QPushButton(self.groupBox_2)
        self.btnAddCat.setGeometry(QtCore.QRect(130, 30, 31, 27))
        self.btnAddCat.setObjectName("btnAddCat")
        self.btnDelCat = QtWidgets.QPushButton(self.groupBox_2)
        self.btnDelCat.setGeometry(QtCore.QRect(250, 90, 31, 27))
        self.btnDelCat.setObjectName("btnDelCat")
        self.lstParametros = QtWidgets.QListWidget(self.groupBox_2)
        self.lstParametros.setGeometry(QtCore.QRect(10, 70, 221, 101))
        self.lstParametros.setObjectName("lstParametros")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Perfil"))
        self.btnImpPerfil.setText(_translate("Dialog", "Importar Perfil"))
        self.btnExpPerfil.setText(_translate("Dialog", "Exportar Perfil"))
        self.lblPerfil.setText(_translate("Dialog", "TextLabel"))
        self.btnNuevoPerfil.setText(_translate("Dialog", "Nuevo Perfil"))
        self.label_4.setText(_translate("Dialog", "Previsualizacion del perfil"))
        self.groupBox.setTitle(_translate("Dialog", "Parametros"))
        self.btnAddParam.setText(_translate("Dialog", "++"))
        self.btnDelParam.setText(_translate("Dialog", "--"))
        self.groupBox_2.setTitle(_translate("Dialog", "Categorias"))
        self.btnAddCat.setText(_translate("Dialog", "++"))
        self.btnDelCat.setText(_translate("Dialog", "--"))

