# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'revisador-form.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(786, 550)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lblimg3 = ScaledLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblimg3.sizePolicy().hasHeightForWidth())
        self.lblimg3.setSizePolicy(sizePolicy)
        self.lblimg3.setMinimumSize(QtCore.QSize(30, 30))
        self.lblimg3.setFrameShape(QtWidgets.QFrame.Box)
        self.lblimg3.setObjectName("lblimg3")
        self.gridLayout.addWidget(self.lblimg3, 2, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblimgppal = ScaledLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblimgppal.sizePolicy().hasHeightForWidth())
        self.lblimgppal.setSizePolicy(sizePolicy)
        self.lblimgppal.setMinimumSize(QtCore.QSize(30, 30))
        self.lblimgppal.setFrameShape(QtWidgets.QFrame.Box)
        self.lblimgppal.setObjectName("lblimgppal")
        self.verticalLayout_2.addWidget(self.lblimgppal)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAnterior = QtWidgets.QPushButton(self.centralwidget)
        self.btnAnterior.setObjectName("btnAnterior")
        self.horizontalLayout.addWidget(self.btnAnterior)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnGetMap = QtWidgets.QPushButton(self.centralwidget)
        self.btnGetMap.setObjectName("btnGetMap")
        self.horizontalLayout.addWidget(self.btnGetMap)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBoxZoom = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxZoom.setMinimum(1)
        self.spinBoxZoom.setMaximum(20)
        self.spinBoxZoom.setObjectName("spinBoxZoom")
        self.horizontalLayout.addWidget(self.spinBoxZoom)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnSiguiente = QtWidgets.QPushButton(self.centralwidget)
        self.btnSiguiente.setObjectName("btnSiguiente")
        self.horizontalLayout.addWidget(self.btnSiguiente)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tablaEventos = QtWidgets.QTableWidget(self.centralwidget)
        self.tablaEventos.setMinimumSize(QtCore.QSize(30, 30))
        self.tablaEventos.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tablaEventos.setColumnCount(6)
        self.tablaEventos.setObjectName("tablaEventos")
        self.tablaEventos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablaEventos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaEventos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaEventos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaEventos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaEventos.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaEventos.setHorizontalHeaderItem(5, item)
        self.verticalLayout_2.addWidget(self.tablaEventos)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 5, 1)
        self.lblimg2 = ScaledLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblimg2.sizePolicy().hasHeightForWidth())
        self.lblimg2.setSizePolicy(sizePolicy)
        self.lblimg2.setMinimumSize(QtCore.QSize(30, 30))
        self.lblimg2.setFrameShape(QtWidgets.QFrame.Box)
        self.lblimg2.setObjectName("lblimg2")
        self.gridLayout.addWidget(self.lblimg2, 1, 0, 1, 1)
        self.lblimg4 = ScaledLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblimg4.sizePolicy().hasHeightForWidth())
        self.lblimg4.setSizePolicy(sizePolicy)
        self.lblimg4.setMinimumSize(QtCore.QSize(30, 30))
        self.lblimg4.setFrameShape(QtWidgets.QFrame.Box)
        self.lblimg4.setObjectName("lblimg4")
        self.gridLayout.addWidget(self.lblimg4, 3, 0, 1, 1)
        self.lblimg5 = ScaledLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblimg5.sizePolicy().hasHeightForWidth())
        self.lblimg5.setSizePolicy(sizePolicy)
        self.lblimg5.setMinimumSize(QtCore.QSize(30, 30))
        self.lblimg5.setFrameShape(QtWidgets.QFrame.Box)
        self.lblimg5.setObjectName("lblimg5")
        self.gridLayout.addWidget(self.lblimg5, 4, 0, 1, 1)
        self.lblimg1 = ScaledLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblimg1.sizePolicy().hasHeightForWidth())
        self.lblimg1.setSizePolicy(sizePolicy)
        self.lblimg1.setMinimumSize(QtCore.QSize(30, 30))
        self.lblimg1.setFrameShape(QtWidgets.QFrame.Box)
        self.lblimg1.setObjectName("lblimg1")
        self.gridLayout.addWidget(self.lblimg1, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 786, 21))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuSesion = QtWidgets.QMenu(self.menubar)
        self.menuSesion.setObjectName("menuSesion")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuMapas = QtWidgets.QMenu(self.menubar)
        self.menuMapas.setObjectName("menuMapas")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbrir = QtWidgets.QAction(MainWindow)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionGuardar = QtWidgets.QAction(MainWindow)
        self.actionGuardar.setObjectName("actionGuardar")
        self.actionExportar_Img = QtWidgets.QAction(MainWindow)
        self.actionExportar_Img.setObjectName("actionExportar_Img")
        self.actionExportar_Map = QtWidgets.QAction(MainWindow)
        self.actionExportar_Map.setObjectName("actionExportar_Map")
        self.actionExportar_CSV = QtWidgets.QAction(MainWindow)
        self.actionExportar_CSV.setObjectName("actionExportar_CSV")
        self.actionExportar_Todo = QtWidgets.QAction(MainWindow)
        self.actionExportar_Todo.setObjectName("actionExportar_Todo")
        self.actionAcerca_de = QtWidgets.QAction(MainWindow)
        self.actionAcerca_de.setObjectName("actionAcerca_de")
        self.actionConfigurarMapas = QtWidgets.QAction(MainWindow)
        self.actionConfigurarMapas.setObjectName("actionConfigurarMapas")
        self.menuArchivo.addAction(self.actionAbrir)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionGuardar)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionSalir)
        self.menuSesion.addAction(self.actionExportar_Img)
        self.menuSesion.addAction(self.actionExportar_Map)
        self.menuSesion.addAction(self.actionExportar_CSV)
        self.menuSesion.addSeparator()
        self.menuSesion.addAction(self.actionExportar_Todo)
        self.menu.addAction(self.actionAcerca_de)
        self.menuMapas.addAction(self.actionConfigurarMapas)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuSesion.menuAction())
        self.menubar.addAction(self.menuMapas.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblimg3.setText(_translate("MainWindow", "TextLabel"))
        self.lblimgppal.setText(_translate("MainWindow", "TextLabel"))
        self.btnAnterior.setText(_translate("MainWindow", "Anterior"))
        self.btnGetMap.setText(_translate("MainWindow", "Descargar Mapa"))
        self.label.setText(_translate("MainWindow", "Zoom"))
        self.btnSiguiente.setText(_translate("MainWindow", "Siguiente"))
        item = self.tablaEventos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Progresiva"))
        item = self.tablaEventos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Latitud"))
        item = self.tablaEventos.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Longitud"))
        item = self.tablaEventos.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Parametro"))
        item = self.tablaEventos.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Caracterisitica"))
        item = self.tablaEventos.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Valor"))
        self.lblimg2.setText(_translate("MainWindow", "TextLabel"))
        self.lblimg4.setText(_translate("MainWindow", "TextLabel"))
        self.lblimg5.setText(_translate("MainWindow", "TextLabel"))
        self.lblimg1.setText(_translate("MainWindow", "TextLabel"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.menuSesion.setTitle(_translate("MainWindow", "Sesion"))
        self.menu.setTitle(_translate("MainWindow", "?"))
        self.menuMapas.setTitle(_translate("MainWindow", "Mapas"))
        self.actionAbrir.setText(_translate("MainWindow", "Abrir"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionGuardar.setText(_translate("MainWindow", "Guardar"))
        self.actionExportar_Img.setText(_translate("MainWindow", "Exportar Imagenes"))
        self.actionExportar_Map.setText(_translate("MainWindow", "Exportar Mapas"))
        self.actionExportar_CSV.setText(_translate("MainWindow", "Exportar CSV"))
        self.actionExportar_Todo.setText(_translate("MainWindow", "Exportar Todo"))
        self.actionAcerca_de.setText(_translate("MainWindow", "Acerca de"))
        self.actionConfigurarMapas.setText(_translate("MainWindow", "Configurar"))

from scaledlabel import ScaledLabel
